spring:
  application:
    name: ftl-oms

#  thymeleaf:
#    prefix: classpath:/email/
#    suffix: .html

  servlet:
    multipart:
      max-file-size: 10MB # Max file size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
      max-request-size: 10MB # Max request size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        # use camel case in database
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    # import sql
    properties.hibernate:
      connection.charSet: UTF-8
      hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.globally_quoted_identifiers: true

  mail:
    host: smtp.gmail.com
    username: op@ftl-express.fr
    password: ftlexpress2017
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
        required: true
    protocol: SMTP

logging:
  level:
    org.springframework: INFO
    org.hibernate: WARN
    org.apache.cxf: WARN
    org.apache.commons.jexl2.JexlEngine: ERROR

info:
  name: ${spring.application.name}
  description: FTL Order Management System
  environment: ${spring.profiles.active}
  version: 1.0.0
