spring:
  application:
    name: api

logging:
  level:
    org.springframework: INFO
    org.hibernate: WARN
    org.apache.cxf: WARN
    org.apache.commons.jexl2.JexlEngine: ERROR


info:
  name: ${spring.application.name}
  description: Cipop API
#  environment: ${spring.profiles.active}
  version: 1.0.0